---
  - name: VM Resize Playbook
    hosts: localhost
    gather_facts: no
    vars:
     auth:
      auth_url: https://<POWERVC>:5000/v3
      project_name: PROJECT-NAME
      username: USERID
      password: PASSWORD
      project_domain_name: PROJECT_DOMAIN_NAME
      user_domain_name: USER_DOMAIN_NAME
    tasks:
       - name: Performing the DELETE SCG Operation
         ibm.powervc.resize_vm:
            auth: "{{ auth }}"
            vm_name: "VM_NAME"
            template_type: "TEMPLATE_TYPE"
         register: result
       - debug:
            var: result
