---
  - name: PowerVC Create VM Playbook
    hosts: localhost
    gather_facts: no
    vars:
     auth:
      auth_url: https://<POWERVC>:5000/v3
      project_name: PROJECT-NAME
      username: USERID
      password: PASSWORD
      project_domain_name: PROJECT_DOMAIN_NAME
      user_domain_name: USER_DOMAIN_NAME
    tasks:  
      - name: Create a new instance and attaches to a network
        ibm.powervc.server:
          auth: "{{ auth }}"
          name: "NAME"
          image: "IMAGE"
          timeout: 200
          max_count: 1
          collocation_rule_name: "COLLOCATION_RULE_NAME"
          nics:
            - network-name: "NETWORK_NAME"
              fixed_ip: "FIXED_IP"
          validate_certs: false
          flavor: "FLAVOR"
          state: present
        register: result
      - name: Disply server info
        debug: var=result


---
  - name: PowerVC Create VM Playbook
    hosts: localhost
    gather_facts: no
      - name: Create a new instance and attaches to a network
        ibm.powervc.server:
          cloud: "CLOUD_NAME"
          name: "VM_NAME"
          image: "VM_IMAGE"
          timeout: 200
          max_count: "COUNT"
          collocation_rule_name: "COLLOCATION_RULE_NAME"
          nics:
            - network_name: "NETWORK_NAME"
              fixed_ip: "FIXED_IP" # "fixed_ip: 192.168.10.20"
          image_volume_override:
            - volume_id: "VOLUME_ID"
              template_id: "TEMPLATE_ID"
          flavor: "FLAVOR_NAME"
          volume_name: ["VOLUME_1","VOLUME_2"]
          state: present
          validate_certs: false
        register: result
      - name: Disply server info
        debug: var=result