---
  - name: VM Volume Detach Playbook
    hosts: localhost
    gather_facts: no
    vars:
     auth:
      auth_url: https://<POWERVC>:5000/v3
      project_name: PROJECT-NAME
      username: USERID
      password: PASSWORD
      project_domain_name: PROJECT_DOMAIN_NAME
      user_domain_name: USER_DOMAIN_NAME
    tasks:
       - name: Perform VM Volume Attach Operations
         ibm.powervc.volume_detach:
            auth: "{{ auth }}"
            name: "NAME"
            volume_name: ["VOLUME_NAME1","VOLUME_NAME2","VOLUME_NAME3"]
            validate_certs: no
         register: result
       - debug:
            var: result
