---
name: Run ibm.powervc collection linting tests

# run linting during pull request to main
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  module-linting-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    name: run module linting
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: install linting test requirements
        run: |
          python -m pip install --upgrade pip
          make install-ansible
          make install-unit-test-requirements
          make install-ansible-lint

      - name: build and install new content as collection
        run: |
          make prep-collection

      - name: run linter
        run: make module-lint
        working-directory: /home/runner/.ansible/collections/ansible_collections/ibm/powervc

      - name: run install-ansible
        run: make ansible-lint
